name: Build and Minify

on:
  push:
    paths:
      - 'lua/**'
  pull_request:
    paths:
      - 'lua/**'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual build'
        required: false
        default: 'Manual build and minify'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version you prefer

      # Step 3: Install luamin via npm
      - name: Install luamin
        run: |
          npm install -g luamin

      # Step 4: Install Lua and LuaRocks
      - name: Install Lua, LuaRocks, and Build Essentials
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.3 luarocks build-essential liblua5.3-dev

      # Step 5: Install LuaFileSystem
      - name: Install LuaFileSystem
        run: |
          sudo luarocks install luafilesystem

      # Step 6: Verify Installations
      - name: Verify Installations
        run: |
          lua -v
          luarocks --version
          luamin -h
          lua -e "require('lfs')"

      # Step 7: Run Makefile Targets
      - name: Run Makefile to Minify Lua Files
        run: |
          make minify

      # Step 8: Upload Minified Lua Files as Artifacts
      - name: Upload Minified Lua Files
        uses: actions/upload-artifact@v3
        with:
          name: minified-lua
          path: |
            lua/**/*.min.lua
