name: GLuaTest Runner

on:
  pull_request:
  workflow_dispatch:
    inputs:
      gamemode:
        description: 'Gamemode to use'
        required: false
        default: 'darkrp'
      debug:
        description: 'Enable debug output'
        required: false
        type: boolean
        default: true

jobs:
  run-tests:
    uses: CFC-Servers/GLuaTest/.github/workflows/run_tests.yml@main
    with:
      gamemode: ${{ inputs.gamemode || 'darkrp' }}
      debug: true
      pre_include: |
        print("[DEBUG] Loading test dependencies...")
        include("autorun/server/sv_radio_init.lua")
        if CLIENT then
          include("autorun/client/cl_radio_init.lua")
        end
        print("[DEBUG] Dependencies loaded")
