name: GLuaTest Runner

on:
  pull_request:
  workflow_dispatch:
    inputs:
      test_group:
        description: 'Test group to run (leave empty for all tests)'
        required: false
        default: ''
      gamemode:
        description: 'Gamemode to use'
        required: false
        default: 'darkrp'

jobs:
  run-tests:
    uses: CFC-Servers/GLuaTest/.github/workflows/run_tests.yml@main
    with:
      gamemode: ${{ inputs.gamemode || 'darkrp' }}
      test_filter: ${{ inputs.test_group }} # Optional
